/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcoesCorretivasRouteImport } from './routes/acoes-corretivas'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as NaoConformidadesRouteImport } from './routes/nao-conformidades'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesCorretivasRoute = AcoesCorretivasRouteImport.update({
  id: '/acoes-corretivas',
  path: '/acoes-corretivas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const NaoConformidadesRoute = NaoConformidadesRouteImport.update({
  id: '/nao-conformidades',
  path: '/nao-conformidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoes-corretivas': typeof AcoesCorretivasRoute
  '/checklists': typeof ChecklistsRoute
  '/nao-conformidades': typeof NaoConformidadesRoute
  '/obras': typeof ObrasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acoes-corretivas': typeof AcoesCorretivasRoute
  '/checklists': typeof ChecklistsRoute
  '/nao-conformidades': typeof NaoConformidadesRoute
  '/obras': typeof ObrasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoes-corretivas': typeof AcoesCorretivasRoute
  '/checklists': typeof ChecklistsRoute
  '/nao-conformidades': typeof NaoConformidadesRoute
  '/obras': typeof ObrasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoes-corretivas'
    | '/checklists'
    | '/nao-conformidades'
    | '/obras'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acoes-corretivas'
    | '/checklists'
    | '/nao-conformidades'
    | '/obras'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/acoes-corretivas'
    | '/checklists'
    | '/nao-conformidades'
    | '/obras'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcoesCorretivasRoute: typeof AcoesCorretivasRoute
  ChecklistsRoute: typeof ChecklistsRoute
  NaoConformidadesRoute: typeof NaoConformidadesRoute
  ObrasRoute: typeof ObrasRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes-corretivas': {
      id: '/acoes-corretivas'
      path: '/acoes-corretivas'
      fullPath: '/acoes-corretivas'
      preLoaderRoute: typeof AcoesCorretivasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nao-conformidades': {
      id: '/nao-conformidades'
      path: '/nao-conformidades'
      fullPath: '/nao-conformidades'
      preLoaderRoute: typeof NaoConformidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcoesCorretivasRoute: AcoesCorretivasRoute,
  ChecklistsRoute: ChecklistsRoute,
  NaoConformidadesRoute: NaoConformidadesRoute,
  ObrasRoute: ObrasRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
